name: Node.js CI/CD

on:
    push:
        branches:
            - '*'
        tags:
            - 'v*'
    pull_request:
        branches:
            - '*'

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   name: Use Node.js
                uses: actions/setup-node@v1
                with:
                    node-version: '16.x'
            -   run: yarn install --frozen-lockfile
            -   run: yarn test
                env:
                    LUNATASK_ACCESS_TOKEN: ${{ secrets.LUNATASK_ACCESS_TOKEN }}
                    LUNATASK_AREA_ID: ${{ secrets.LUNATASK_AREA_ID }}
                    LUNATASK_GOAL_ID: ${{ secrets.LUNATASK_GOAL_ID }}

    build-and-publish:
        needs: test
        runs-on: ubuntu-latest
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        steps:
            -   uses: actions/checkout@v2
            -   name: Use Node.js
                uses: actions/setup-node@v1
                with:
                    node-version: '16.x'
                    registry-url: 'https://registry.npmjs.org/'

            -   name: Extract version from tag
                run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

            -   name: Update package.json version
                run: npm version ${{ env.VERSION }} --no-git-tag-version

            -   run: yarn install --frozen-lockfile
            -   run: yarn build
            -   run: npm publish --access public
                env:
                    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
